# Generated by Django 5.1 on 2024-08-29 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos_identite/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type_document', models.CharField(choices=[('identite', 'Identite'), ('acte', 'Acte'), ('procuration', 'Procuration'), ('mandat', 'Mandat')], max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('fichier', models.FileField(upload_to='documents/')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='chambre.membre')),
            ],
        ),
    ]
